s=set()
n1=input("enter your number:")
n2=input("enter your number:")
n3=input("enter your number:")
n4=input("enter your number:")
n5=input("enter your number:")
n6=input("enter your number:")
n7=input("enter your number:")
n8=input("enter your number:")
s.add(n1)
s.add(n2)
s.add(n3)
s.add(n4)
s.add(n5)
s.add(n6)
s.add(n7)
s.add(n8)
print(s)